### ISSUE TITLE
Yada

### ISSUE THREAD

**Issue by NUIYADA** [stellar-expert/stellar-expert-explorer#676]
"loadAllHorizonRecords is not defined" at https://stellar.expert/explorer/public/account/GC3THLTAF2IEILDRMVV4LSLK3YMVND2AKKXOPZNDJLZHZLNFMSXKKMD2?filter=active-offers
ReferenceError: loadAllHorizonRecords is not defined
    at a (https://stellar.expert/78.b5998321afaa2a065e1734e85d126f85.js:1:4000)
    at https://stellar.expert/explorer.464655a711f9b758444f183f822eb553.js:1:71521
    at https://stellar.expert/app.5706ce3efcf37673bddb.js:2:58205
    at Object.ya [as useState] (https://stellar.expert/app.5706ce3efcf37673bddb.js:2:129852)
Mozilla/5.0 (Linux; Android 11; RMX3231

**Comment by NUIYADA** [comment]
"loadAllHorizonRecords is not defined" at https://stellar.expert/explorer/public/account/GC3THLTAF2IEILDRMVV4LSLK3YMVND2AKKXOPZNDJLZHZLNFMSXKKMD2?filter=active-offers
ReferenceError: loadAllHorizonRecords is not defined
    at a (https://stellar.expert/78.b5998321afaa2a065e1734e85d126f85.js:1:4000)
    at https://stellar.expert/explorer.464655a711f9b758444f183f822eb553.js:1:71521
    at https://stellar.expert/app.5706ce3efcf37673bddb.js:2:58205
    at Object.ya [as useState] (https://stellar.expert/app.5706ce3efcf37673bddb.js:2:129852)
Mozilla/5.0 (Linux; Android 11; RMX3231
