### ISSUE TITLE
Unhandle Error

### ISSUE THREAD

**Issue by badedokun** [stellar-expert/stellar-expert-explorer#706]
I clicked on an asset card in explorer and received the error message below:

"Cannot read properties of undefined (reading 'map')" at https://stellar.expert/explorer/public/account/GBYYWKVST3FMFEIHEYEKVJBYFW5GXWUVL737A6HU4XUVZZUY2B4TNQ5M
TypeError: Cannot read properties of undefined (reading 'map')
    at v (https://stellar.expert/513.e51d759b7caf435593eb10c31a91ebfb.js:2:16111)
    at sa (https://stellar.expert/app.c02fd08275e7f3aba0e3.js:2:268741)
    at Ka (https://stellar.expert/app.c02fd08275e7f3aba0e3.js:2:278259)
    at $s (https://stellar.expert/app.c02fd08275e7f3aba0e3.js:2:321796)
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

**Comment by badedokun** [comment]
The asset is the pool for XLM<>USDO.
