### ISSUE TITLE
"Asset is not defined" red message in my Stellar Expert Explorer wallet

### ISSUE THREAD

**Issue by meparadis** [stellar-expert/stellar-expert-explorer#818]
I get the following message when I try to see my holdings in Stellar Expert : 

ReferenceError: asset is not defined
    at h (https://stellar.expert/explorer.cc874305274e17d877072586dc080a90.js:1:26757)
    at aa (https://stellar.expert/app.d9749cdaf062881856bb.js:2:432718)
    at Ws (https://stellar.expert/app.d9749cdaf062881856bb.js:2:484843)
    at Cu (https://stellar.expert/app.d9749cdaf062881856bb.js:2:472121)
    at Ou (https://stellar.expert/app.d9749cdaf062881856bb.js:2:472049)
    at Au (https://stellar.expert/app.d9749cdaf062881856bb.js:2:471912)
    at bu (https://stellar.expert/app.d9749cdaf062881856bb.js:2:468899)
    at https://stellar.expert/app.d9749cdaf062881856bb.js:2:418637
    at t.unstable_runWithPriority (https://stellar.expert/app.d9749cdaf062881856bb.js:2:513298)
    at $o (https://stellar.expert/app.d9749cdaf062881856bb.js:2:418414)

**Comment by orbitlens** [comment]
Could you please provide your account address or the link to the webpage where you see this error?

**Comment by meparadis** [comment]
GAXOCT452OQUY6KFQOIP4RCHOPZGLLRGRFEDAZMK7A2SSY7REWF7QX2C

https://stellar.expert/explorer/public/account/GAXOCT452OQUY6KFQOIP4RCHOPZGLLRGRFEDAZMK7A2SSY7REWF7QX2C

**Comment by orbitlens** [comment]
Fixed. Thanks for the bug report!
