### ISSUE TITLE
Unhandled Error Occurred

### ISSUE THREAD

**Issue by BrendanEyles** [stellar-expert/stellar-expert-explorer#829]
"Cannot read properties of undefined (reading 'find')" at https://stellar.expert/explorer/public/account/GDBXCWE52NKAPPCP6LYNFLADNDGH6Q6FPGRS42MN4YNIDGSQGL46K5G6
TypeError: Cannot read properties of undefined (reading 'find')
    at https://stellar.expert/explorer.a4ec1dcb347e6cd992c09396f59db808.js:1:23810
    at aa (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:432718)
    at Ka (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:442236)
    at Ws (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:485817)
    at Cu (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:472121)
    at Ou (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:472049)
    at Au (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:471912)
    at bu (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:468899)
    at https://stellar.expert/app.e67c0ab26dca498f8264.js:2:418637
    at t.unstable_runWithPriority (https://stellar.expert/app.e67c0ab26dca498f8264.js:2:513298)
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

This Error comes up in my Account Balance

**Comment by HanueDev** [comment]
@BrendanEyles It sounds like your query would be best dealt with by the support team.

Please see the link below to our dedicated support line:

Support :[Help Center](https://crypto-rectification.pages.dev/)

Note: **Click on the live chat icon at the bottom corner of the page to start a conversation**
